[package]
name = "colors"
version = "0.1.0"
authors = ["Emily"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.41.0"
image = "0.19.0"
cgmath = "0.18.0"
